defaultModel: openai/v4-flash

providers:
  openai:
    api: openai
    apiKey: ${MODEL_API_KEY:}
    baseUrl: ${MODEL_BASE_URL:}
    models:
      - id: v4-flash
        name: ${MODEL_NAME:deepseek-v4-flash}
        stream: false
        temperature: 0.1
        maxTokens: 3000
        enableThinking: false
